/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as BienvenidaRouteImport } from './routes/bienvenida'
import { Route as AppRutaRouteImport } from './routes/_app/ruta'
import { Route as DiagnosticoIndexRouteImport } from './routes/diagnostico.index'
import { Route as DiagnosticoResultadoRouteImport } from './routes/diagnostico.resultado'
import { Route as AppIntentosIntentoIdRouteImport } from './routes/_app/intentos.$intentoId'
import { Route as AppNodosNodoIdCuestionarioRouteImport } from './routes/_app/nodos.$nodoId.cuestionario'
import { Route as AppNodosNodoIdLeccionRouteImport } from './routes/_app/nodos.$nodoId.leccion'
import { Route as AppNodosNodoIdRetoRouteImport } from './routes/_app/nodos.$nodoId.reto'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenidaRoute = BienvenidaRouteImport.update({
  id: '/bienvenida',
  path: '/bienvenida',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRutaRoute = AppRutaRouteImport.update({
  id: '/ruta',
  path: '/ruta',
  getParentRoute: () => AppRoute,
} as any)
const DiagnosticoIndexRoute = DiagnosticoIndexRouteImport.update({
  id: '/diagnostico/',
  path: '/diagnostico/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoResultadoRoute = DiagnosticoResultadoRouteImport.update({
  id: '/diagnostico/resultado',
  path: '/diagnostico/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIntentosIntentoIdRoute = AppIntentosIntentoIdRouteImport.update({
  id: '/intentos/$intentoId',
  path: '/intentos/$intentoId',
  getParentRoute: () => AppRoute,
} as any)
const AppNodosNodoIdCuestionarioRoute =
  AppNodosNodoIdCuestionarioRouteImport.update({
    id: '/nodos/$nodoId/cuestionario',
    path: '/nodos/$nodoId/cuestionario',
    getParentRoute: () => AppRoute,
  } as any)
const AppNodosNodoIdLeccionRoute = AppNodosNodoIdLeccionRouteImport.update({
  id: '/nodos/$nodoId/leccion',
  path: '/nodos/$nodoId/leccion',
  getParentRoute: () => AppRoute,
} as any)
const AppNodosNodoIdRetoRoute = AppNodosNodoIdRetoRouteImport.update({
  id: '/nodos/$nodoId/reto',
  path: '/nodos/$nodoId/reto',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bienvenida': typeof BienvenidaRoute
  '/ruta': typeof AppRutaRoute
  '/diagnostico/resultado': typeof DiagnosticoResultadoRoute
  '/diagnostico/': typeof DiagnosticoIndexRoute
  '/intentos/$intentoId': typeof AppIntentosIntentoIdRoute
  '/nodos/$nodoId/cuestionario': typeof AppNodosNodoIdCuestionarioRoute
  '/nodos/$nodoId/leccion': typeof AppNodosNodoIdLeccionRoute
  '/nodos/$nodoId/reto': typeof AppNodosNodoIdRetoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bienvenida': typeof BienvenidaRoute
  '/ruta': typeof AppRutaRoute
  '/diagnostico/resultado': typeof DiagnosticoResultadoRoute
  '/diagnostico': typeof DiagnosticoIndexRoute
  '/intentos/$intentoId': typeof AppIntentosIntentoIdRoute
  '/nodos/$nodoId/cuestionario': typeof AppNodosNodoIdCuestionarioRoute
  '/nodos/$nodoId/leccion': typeof AppNodosNodoIdLeccionRoute
  '/nodos/$nodoId/reto': typeof AppNodosNodoIdRetoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/bienvenida': typeof BienvenidaRoute
  '/_app/ruta': typeof AppRutaRoute
  '/diagnostico/resultado': typeof DiagnosticoResultadoRoute
  '/diagnostico/': typeof DiagnosticoIndexRoute
  '/_app/intentos/$intentoId': typeof AppIntentosIntentoIdRoute
  '/_app/nodos/$nodoId/cuestionario': typeof AppNodosNodoIdCuestionarioRoute
  '/_app/nodos/$nodoId/leccion': typeof AppNodosNodoIdLeccionRoute
  '/_app/nodos/$nodoId/reto': typeof AppNodosNodoIdRetoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bienvenida'
    | '/ruta'
    | '/diagnostico/resultado'
    | '/diagnostico/'
    | '/intentos/$intentoId'
    | '/nodos/$nodoId/cuestionario'
    | '/nodos/$nodoId/leccion'
    | '/nodos/$nodoId/reto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bienvenida'
    | '/ruta'
    | '/diagnostico/resultado'
    | '/diagnostico'
    | '/intentos/$intentoId'
    | '/nodos/$nodoId/cuestionario'
    | '/nodos/$nodoId/leccion'
    | '/nodos/$nodoId/reto'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/bienvenida'
    | '/_app/ruta'
    | '/diagnostico/resultado'
    | '/diagnostico/'
    | '/_app/intentos/$intentoId'
    | '/_app/nodos/$nodoId/cuestionario'
    | '/_app/nodos/$nodoId/leccion'
    | '/_app/nodos/$nodoId/reto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BienvenidaRoute: typeof BienvenidaRoute
  DiagnosticoResultadoRoute: typeof DiagnosticoResultadoRoute
  DiagnosticoIndexRoute: typeof DiagnosticoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenida': {
      id: '/bienvenida'
      path: '/bienvenida'
      fullPath: '/bienvenida'
      preLoaderRoute: typeof BienvenidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ruta': {
      id: '/_app/ruta'
      path: '/ruta'
      fullPath: '/ruta'
      preLoaderRoute: typeof AppRutaRouteImport
      parentRoute: typeof AppRoute
    }
    '/diagnostico/': {
      id: '/diagnostico/'
      path: '/diagnostico'
      fullPath: '/diagnostico/'
      preLoaderRoute: typeof DiagnosticoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico/resultado': {
      id: '/diagnostico/resultado'
      path: '/diagnostico/resultado'
      fullPath: '/diagnostico/resultado'
      preLoaderRoute: typeof DiagnosticoResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/intentos/$intentoId': {
      id: '/_app/intentos/$intentoId'
      path: '/intentos/$intentoId'
      fullPath: '/intentos/$intentoId'
      preLoaderRoute: typeof AppIntentosIntentoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodos/$nodoId/cuestionario': {
      id: '/_app/nodos/$nodoId/cuestionario'
      path: '/nodos/$nodoId/cuestionario'
      fullPath: '/nodos/$nodoId/cuestionario'
      preLoaderRoute: typeof AppNodosNodoIdCuestionarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodos/$nodoId/leccion': {
      id: '/_app/nodos/$nodoId/leccion'
      path: '/nodos/$nodoId/leccion'
      fullPath: '/nodos/$nodoId/leccion'
      preLoaderRoute: typeof AppNodosNodoIdLeccionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodos/$nodoId/reto': {
      id: '/_app/nodos/$nodoId/reto'
      path: '/nodos/$nodoId/reto'
      fullPath: '/nodos/$nodoId/reto'
      preLoaderRoute: typeof AppNodosNodoIdRetoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppRutaRoute: typeof AppRutaRoute
  AppIntentosIntentoIdRoute: typeof AppIntentosIntentoIdRoute
  AppNodosNodoIdCuestionarioRoute: typeof AppNodosNodoIdCuestionarioRoute
  AppNodosNodoIdLeccionRoute: typeof AppNodosNodoIdLeccionRoute
  AppNodosNodoIdRetoRoute: typeof AppNodosNodoIdRetoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppRutaRoute: AppRutaRoute,
  AppIntentosIntentoIdRoute: AppIntentosIntentoIdRoute,
  AppNodosNodoIdCuestionarioRoute: AppNodosNodoIdCuestionarioRoute,
  AppNodosNodoIdLeccionRoute: AppNodosNodoIdLeccionRoute,
  AppNodosNodoIdRetoRoute: AppNodosNodoIdRetoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BienvenidaRoute: BienvenidaRoute,
  DiagnosticoResultadoRoute: DiagnosticoResultadoRoute,
  DiagnosticoIndexRoute: DiagnosticoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
